spring.application.name=job-report-batch
spring.main.web-application-type=none
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.enabled=true
spring.sql.init.mode=never

logging.level.com.example.jobreport=INFO
